// Push fan-out tests, written against the cancellation notices from
// migration 0035.
//
// Cancellations are the case worth pinning down. Every other announcement is
// typed by a human who can see who they're addressing before they hit post; a
// cancellation is generated by a delete trigger and pushed by a fire-and-forget
// call from app/event/[id].tsx, with nobody reading it first. If the targeting
// is wrong, the failure is a parent driving to an empty field — and nothing in
// the logs looks unusual.
//
// Run:  deno test --allow-none supabase/functions/tests/

import { assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { FakeSupabase, Row } from "./fakeSupabase.ts";
import {
  buildPushMessages,
  chunkMessages,
  collectPushTokens,
  filterOptedIn,
  PushableAnnouncement,
  resolveRecipientIds,
} from "../_shared/announcementPush.ts";

// ---------------------------------------------------------------------------
// Fixture: one club, two teams, a coach who cancels things, and five families.
// ---------------------------------------------------------------------------

const CLUB = "club-williams";
const OTHER_CLUB = "club-rival";
const TEAM = "team-u12";
const OTHER_TEAM = "team-u14";

const COACH = "user-coach-sam"; // the author of every notice below
const DIRECTOR = "user-director-ada";
const COACH_TWO = "user-coach-jordan";
const PARENT_A = "user-parent-a";
const PARENT_B = "user-parent-b";
const PARENT_C = "user-parent-c"; // on OTHER_TEAM
const PARENT_MUTED = "user-parent-muted";
const PARENT_NO_DEVICE = "user-parent-no-device";
const OUTSIDER = "user-parent-rival-club";
const RIVAL_DIRECTOR = "user-director-rival-club";

function profile(id: string, role: string, opts: Partial<Row> = {}): Row {
  return {
    id,
    role,
    club_id: CLUB,
    full_name: id,
    notify_announcements: true,
    ...opts,
  };
}

function baseTables(): Record<string, Row[]> {
  return {
    profiles: [
      profile(COACH, "coach", { full_name: "Coach Sam" }),
      profile(DIRECTOR, "director"),
      profile(COACH_TWO, "coach"),
      profile(PARENT_A, "parent"),
      profile(PARENT_B, "parent"),
      profile(PARENT_C, "parent"),
      profile(PARENT_MUTED, "parent", { notify_announcements: false }),
      profile(PARENT_NO_DEVICE, "parent"),
      profile(OUTSIDER, "parent", { club_id: OTHER_CLUB }),
      // Staff at another club. Exists so "all coaches and directors" can be
      // caught being read as global rather than club-scoped.
      profile(RIVAL_DIRECTOR, "director", { club_id: OTHER_CLUB }),
    ],
    players: [
      { id: "player-1", team_id: TEAM, parent_id: PARENT_A },
      { id: "player-2", team_id: TEAM, parent_id: PARENT_B },
      // Two siblings on the same team, one parent — the duplicate-token case.
      { id: "player-3", team_id: TEAM, parent_id: PARENT_B },
      { id: "player-4", team_id: TEAM, parent_id: PARENT_MUTED },
      { id: "player-5", team_id: TEAM, parent_id: PARENT_NO_DEVICE },
      // Unclaimed player: a record with no parent account attached yet.
      { id: "player-6", team_id: TEAM, parent_id: null },
      { id: "player-7", team_id: OTHER_TEAM, parent_id: PARENT_C },
      // The coach's own kid, on the team he coaches. Common in small clubs,
      // and the only way the author exclusion in the parent branches gets
      // exercised at all.
      { id: "player-8", team_id: TEAM, parent_id: COACH },
    ],
    push_tokens: [
      { user_id: COACH, expo_push_token: "tok-coach", enabled: true },
      { user_id: DIRECTOR, expo_push_token: "tok-director", enabled: true },
      { user_id: COACH_TWO, expo_push_token: "tok-coach-two", enabled: true },
      { user_id: PARENT_A, expo_push_token: "tok-a", enabled: true },
      { user_id: PARENT_B, expo_push_token: "tok-b", enabled: true },
      { user_id: PARENT_C, expo_push_token: "tok-c", enabled: true },
      { user_id: PARENT_MUTED, expo_push_token: "tok-muted", enabled: true },
      { user_id: RIVAL_DIRECTOR, expo_push_token: "tok-rival", enabled: true },
      // One household tablet both parents registered. Distinct rows, same
      // token — Expo would deliver two identical banners to one device.
      { user_id: PARENT_A, expo_push_token: "tok-family-tablet", enabled: true },
      { user_id: PARENT_B, expo_push_token: "tok-family-tablet", enabled: true },
      // Signed out on this device: the row survives, the send must not.
      { user_id: PARENT_NO_DEVICE, expo_push_token: "tok-stale", enabled: false },
    ],
    announcement_player_targets: [],
    clubs: [{ id: CLUB, name: "Williams Soccer Clinic" }],
    teams: [{ id: TEAM, name: "U12 Boys" }],
  };
}

function cancellation(overrides: Partial<PushableAnnouncement> = {}): PushableAnnouncement {
  return {
    id: "ann-cancel-1",
    club_id: CLUB,
    team_id: TEAM,
    author_id: COACH,
    title: "Cancelled: Thursday Small Group",
    pinned: false,
    target_type: "team",
    ...overrides,
  };
}

/** The full fan-out, in the order index.ts runs it. */
async function fanOut(db: FakeSupabase, ann: PushableAnnouncement) {
  const recipients = await resolveRecipientIds(db, ann);
  const optedIn = await filterOptedIn(db, recipients);
  const tokens = await collectPushTokens(db, optedIn);
  return { recipients, optedIn, tokens };
}

const sorted = (xs: string[]) => [...xs].sort();

// ---------------------------------------------------------------------------
// Recipient targeting
// ---------------------------------------------------------------------------

Deno.test("team cancellation reaches that team's parents and the other staff", async () => {
  const db = new FakeSupabase(baseTables());
  const { recipients } = await fanOut(db, cancellation());

  assertEquals(
    sorted(recipients),
    sorted([DIRECTOR, COACH_TWO, PARENT_A, PARENT_B, PARENT_MUTED, PARENT_NO_DEVICE])
  );
});

Deno.test("the coach who cancelled is not pushed their own cancellation", async () => {
  const db = new FakeSupabase(baseTables());
  const { recipients } = await fanOut(db, cancellation());
  assertEquals(recipients.includes(COACH), false);
});

Deno.test("a cancellation never reaches a parent on a different team", async () => {
  const db = new FakeSupabase(baseTables());
  const { recipients } = await fanOut(db, cancellation());
  assertEquals(recipients.includes(PARENT_C), false);
});

Deno.test("a cancellation never leaves the club", async () => {
  const db = new FakeSupabase(baseTables());
  for (const target of ["team", "everyone"] as const) {
    const { recipients } = await fanOut(db, cancellation({ target_type: target }));
    assertEquals(recipients.includes(OUTSIDER), false, `leaked to parent on ${target}`);
    // The team branch selects "coaches and directors in this club". Without the
    // club filter it reads as every coach and director on the platform, which
    // is a cross-tenant leak that no parent-side assertion would catch.
    assertEquals(recipients.includes(RIVAL_DIRECTOR), false, `leaked to staff on ${target}`);
  }
});

Deno.test("a player-targeted cancellation reaches only those families", async () => {
  // The trigger emits target_type='players' when the cancelled session had a
  // specific roster, so the blast radius must stay at those parents — no staff.
  const tables = baseTables();
  tables.announcement_player_targets = [
    { announcement_id: "ann-cancel-1", player_id: "player-1" },
    { announcement_id: "ann-cancel-1", player_id: "player-2" },
    // Belongs to a different notice; must be ignored.
    { announcement_id: "ann-other", player_id: "player-7" },
  ];
  const db = new FakeSupabase(tables);
  const { recipients } = await fanOut(db, cancellation({ target_type: "players" }));

  assertEquals(sorted(recipients), sorted([PARENT_A, PARENT_B]));
});

Deno.test("a coach cancelling their own child's session is not pushed it", async () => {
  // The author exclusion has to be applied per-parent, not just to the staff
  // list — a coach who is also a parent on the roster arrives through the
  // players lookup, well after the staff query has already excluded them.
  const tables = baseTables();
  tables.announcement_player_targets = [
    { announcement_id: "ann-cancel-1", player_id: "player-1" },
    { announcement_id: "ann-cancel-1", player_id: "player-8" }, // the coach's kid
  ];
  const db = new FakeSupabase(tables);
  const { recipients } = await fanOut(db, cancellation({ target_type: "players" }));

  assertEquals(sorted(recipients), [PARENT_A]);
});

Deno.test("an unclaimed player contributes no recipient, and doesn't crash", async () => {
  // players.parent_id is nullable — a roster record can exist before the family
  // signs up. Cancelling that player's session must be a no-op for them.
  const tables = baseTables();
  tables.announcement_player_targets = [
    { announcement_id: "ann-cancel-1", player_id: "player-6" },
  ];
  const db = new FakeSupabase(tables);
  const { recipients } = await fanOut(db, cancellation({ target_type: "players" }));
  assertEquals(recipients, []);
});

Deno.test("a club-wide cancellation reaches every member except the author", async () => {
  const db = new FakeSupabase(baseTables());
  const { recipients } = await fanOut(
    db,
    cancellation({ target_type: "everyone", team_id: null })
  );

  assertEquals(
    sorted(recipients),
    sorted([DIRECTOR, COACH_TWO, PARENT_A, PARENT_B, PARENT_C, PARENT_MUTED, PARENT_NO_DEVICE])
  );
});

Deno.test("a club-wide cancellation filters on club, not on the null team_id", async () => {
  // Regression guard: target_type='everyone' carries team_id = null. If the
  // team branch were ever reached with that, `.eq("team_id", null)` matches the
  // unassigned players instead of erroring.
  const db = new FakeSupabase(baseTables());
  await resolveRecipientIds(db, cancellation({ target_type: "everyone", team_id: null }));

  assertEquals(db.queriesFor("players").length, 0);
  const [profileQuery] = db.queriesFor("profiles");
  assertEquals(profileQuery.filters, [
    { op: "eq", column: "club_id", value: CLUB },
    { op: "neq", column: "id", value: COACH },
  ]);
});

// ---------------------------------------------------------------------------
// Preferences and devices
// ---------------------------------------------------------------------------

Deno.test("a parent who muted announcements is targeted but not pinged", async () => {
  // Deliberate: muting the ping is not muting the news. They stay a recipient
  // so the notice still appears in their feed; they just drop out before Expo.
  const db = new FakeSupabase(baseTables());
  const { recipients, optedIn, tokens } = await fanOut(db, cancellation());

  assertEquals(recipients.includes(PARENT_MUTED), true);
  assertEquals(optedIn.includes(PARENT_MUTED), false);
  assertEquals(tokens.includes("tok-muted"), false);
});

Deno.test("a disabled device token is not sent to", async () => {
  const db = new FakeSupabase(baseTables());
  const { optedIn, tokens } = await fanOut(db, cancellation());

  assertEquals(optedIn.includes(PARENT_NO_DEVICE), true);
  assertEquals(tokens.includes("tok-stale"), false);
});

Deno.test("a parent with two players on the team is pushed once", async () => {
  const db = new FakeSupabase(baseTables());
  const { recipients, tokens } = await fanOut(db, cancellation());

  assertEquals(recipients.filter((r) => r === PARENT_B).length, 1);
  assertEquals(tokens.filter((t) => t === "tok-b").length, 1);
});

Deno.test("one device shared by two parents gets a single banner", async () => {
  // Distinct users, distinct token rows, same physical device. Deduplicating
  // recipients is not enough to catch this; it has to happen on the tokens.
  const db = new FakeSupabase(baseTables());
  const { tokens } = await fanOut(db, cancellation());

  assertEquals(tokens.filter((t) => t === "tok-family-tablet").length, 1);
  assertEquals(
    sorted(tokens),
    sorted(["tok-director", "tok-coach-two", "tok-a", "tok-b", "tok-family-tablet"])
  );
});

Deno.test("nobody with a device means no Expo request at all", async () => {
  const tables = baseTables();
  tables.push_tokens = [];
  const db = new FakeSupabase(tables);
  const { recipients, tokens } = await fanOut(db, cancellation());

  assertEquals(recipients.length > 0, true);
  assertEquals(tokens, []);
  assertEquals(chunkMessages(buildPushMessages({
    tokens,
    announcement: cancellation(),
    authorName: "Coach Sam",
    teamName: "U12 Boys",
    clubName: "Williams Soccer Clinic",
  })), []);
});

Deno.test("token collection is skipped entirely when everyone opted out", async () => {
  const tables = baseTables();
  tables.profiles = tables.profiles.map((p) => ({ ...p, notify_announcements: false }));
  const db = new FakeSupabase(tables);
  const { optedIn, tokens } = await fanOut(db, cancellation());

  assertEquals(optedIn, []);
  assertEquals(tokens, []);
  // An unguarded `.in("user_id", [])` would return every token row in the fake
  // and, in PostgREST, is an easy way to push to the whole club.
  assertEquals(db.queriesFor("push_tokens").length, 0);
});

// ---------------------------------------------------------------------------
// Notification payload
// ---------------------------------------------------------------------------

Deno.test("a single-session cancellation reads as team then coach then title", async () => {
  const messages = buildPushMessages({
    tokens: ["tok-a"],
    announcement: cancellation(),
    authorName: "Coach Sam",
    teamName: "U12 Boys",
    clubName: "Williams Soccer Clinic",
  });

  assertEquals(messages.length, 1);
  assertEquals(messages[0].title, "U12 Boys");
  assertEquals(messages[0].body, "Coach Sam: Cancelled: Thursday Small Group");
  assertEquals(messages[0].sound, "default");
});

Deno.test("a folded series cancellation carries the count into the lock screen", async () => {
  // 0035 folds a cancelled block into one notice titled "N sessions
  // cancelled: X". The count has to survive into the push body, or a parent
  // reads "Cancelled: Thursday Small Group" and assumes it's just the one.
  const messages = buildPushMessages({
    tokens: ["tok-a"],
    announcement: cancellation({ title: "4 sessions cancelled: Thursday Small Group" }),
    authorName: "Coach Sam",
    teamName: "U12 Boys",
    clubName: "Williams Soccer Clinic",
  });

  assertEquals(messages[0].body, "Coach Sam: 4 sessions cancelled: Thursday Small Group");
});

Deno.test("a club-wide cancellation falls back to the club name as the title", async () => {
  const messages = buildPushMessages({
    tokens: ["tok-a"],
    announcement: cancellation({ target_type: "everyone", team_id: null }),
    authorName: "Coach Sam",
    teamName: null,
    clubName: "Williams Soccer Clinic",
  });

  assertEquals(messages[0].title, "Williams Soccer Clinic");
  assertEquals(messages[0].data.teamId, null);
});

Deno.test("the payload deep-links to the notice so a tap opens the feed", async () => {
  const messages = buildPushMessages({
    tokens: ["tok-a"],
    announcement: cancellation(),
    authorName: "Coach Sam",
    teamName: "U12 Boys",
    clubName: "Williams Soccer Clinic",
  });

  // Not "cancellation": the client routes on data.type, and a cancellation is
  // still an announcement row. A new value here would silently dead-end taps.
  assertEquals(messages[0].data, {
    type: "announcement",
    announcementId: "ann-cancel-1",
    teamId: TEAM,
  });
});

Deno.test("a cancellation is not decorated with the pin emoji unless pinned", async () => {
  const plain = buildPushMessages({
    tokens: ["tok-a"],
    announcement: cancellation(),
    authorName: "Coach Sam",
    teamName: "U12 Boys",
    clubName: null,
  });
  const pinned = buildPushMessages({
    tokens: ["tok-a"],
    announcement: cancellation({ pinned: true }),
    authorName: "Coach Sam",
    teamName: "U12 Boys",
    clubName: null,
  });

  assertEquals(plain[0].body.startsWith("Coach Sam:"), true);
  assertEquals(pinned[0].body.startsWith("📌 Coach Sam:"), true);
});

Deno.test("a missing author name degrades instead of printing undefined", async () => {
  const messages = buildPushMessages({
    tokens: ["tok-a"],
    announcement: cancellation(),
    authorName: null,
    teamName: null,
    clubName: null,
  });

  assertEquals(messages[0].title, "ClubHQ");
  assertEquals(messages[0].body, "Someone: Cancelled: Thursday Small Group");
});

// ---------------------------------------------------------------------------
// Batching
// ---------------------------------------------------------------------------

Deno.test("a large club's cancellation is split into Expo-sized batches", async () => {
  const tokens = Array.from({ length: 250 }, (_, i) => `tok-${i}`);
  const batches = chunkMessages(
    buildPushMessages({
      tokens,
      announcement: cancellation(),
      authorName: "Coach Sam",
      teamName: "U12 Boys",
      clubName: null,
    })
  );

  assertEquals(batches.map((b) => b.length), [100, 100, 50]);
  // Every token appears exactly once across the batches — an off-by-one in the
  // slice window would either drop the tail or double-send a boundary token.
  assertEquals(batches.flat().map((m) => m.to), tokens);
});

Deno.test("an exact multiple of the batch size produces no trailing empty batch", async () => {
  const batches = chunkMessages(
    buildPushMessages({
      tokens: Array.from({ length: 200 }, (_, i) => `tok-${i}`),
      announcement: cancellation(),
      authorName: "Coach Sam",
      teamName: null,
      clubName: null,
    })
  );

  assertEquals(batches.length, 2);
});

// ---------------------------------------------------------------------------
// Cross-layer: the push path must match what the trigger produces
// ---------------------------------------------------------------------------

Deno.test("every target_type the cancellation trigger emits resolves recipients", async () => {
  // 0035's announce_event_cancellation() mirrors events_read and can emit any
  // of these three. A target_type the push function doesn't handle would fall
  // into the `else` branch and get treated as a team notice.
  const tables = baseTables();
  tables.announcement_player_targets = [
    { announcement_id: "ann-cancel-1", player_id: "player-1" },
  ];

  const cases: { target: PushableAnnouncement["target_type"]; team: string | null }[] = [
    { target: "players", team: TEAM },
    { target: "team", team: TEAM },
    { target: "everyone", team: null },
  ];

  for (const { target, team } of cases) {
    const scoped = new FakeSupabase(tables);
    const recipients = await resolveRecipientIds(
      scoped,
      cancellation({ target_type: target, team_id: team })
    );
    assertEquals(recipients.length > 0, true, `no recipients for target_type=${target}`);
  }
});

Deno.test("the deep-link type stays 'announcement' for every target_type", async () => {
  // A cancellation is still an announcement row, and the client routes on
  // data.type. Introducing a "cancellation" type here would dead-end the tap.
  for (const target of ["players", "team", "everyone"] as const) {
    const [message] = buildPushMessages({
      tokens: ["tok-a"],
      announcement: cancellation({ target_type: target }),
      authorName: "Coach Sam",
      teamName: null,
      clubName: null,
    });
    assertEquals(message.data.type, "announcement", `wrong type for ${target}`);
  }
});
